#!/dis/sh.dis
load std
autoload=(std)

bind -a '#o' /dev	# sdio
bind -a '#φ' /dev	# efuse
bind -a '#T' /dev	# sheeva
bind -a '#B' /dev	# boot

mount {mntgen} /n
memfs /tmp

echo static | run /netrc

echo debug off > '#o'/ctl
echo init > '#o'/ctl
cat '#o'/ctl

dossrv  -f '#o'/data -m /n/dos
#unmount /n/dos

while {} {
	echo shell...
	sh -i
	echo
}
