#!/dis/sh.dis

load std

echo -n network...
x=`{cat /net/ipifc/clone}
echo bind ether /net/ether0 >/net/ipifc/$x/ctl

ip=192.168.1.50
ipmask=255.255.255.0
ipgw=192.168.1.254
sys=sheeva0
dom=local
auth=''
fs=''
dns=''

echo add $ip $ipmask >/net/ipifc/$x/ctl
echo add 0 0 $ipgw >/net/iproute
{
	echo 'ip='$ip 'ipmask='$ipmask 'ipgw='$ipgw
	echo '	sys='$sys
	echo '	dom='$sys.$dom
	echo '	auth='$auth
	echo '	fs='$fs
	echo '	dns='$dns
} >/net/ndb

ndb/cs
ndb/dns -r &
echo

mount {mntgen} /n
memfs /tmp

echo -n listen telnet...
listen -A net!*!telnet {sh -i >[2=1]} &
echo
while {} {
	echo shell...
	sh -i
	echo
}
